[project]
name = "agenticrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agentevals>=0.0.9",
    "chromadb>=1.2.2",
    "duckduckgo-search>=8.1.1",
    "langchain>=1.0.2",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.0",
    "langchain-tavily>=0.2.12",
    "langchainhub>=0.1.21",
    "langgraph>=1.0.1",
    "langgraph-checkpoint-postgres>=3.0.0",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "langgraph-cli[inmem]>=0.4.4",
    "langgraph-supervisor>=0.0.30",
    "langmem>=0.0.30",
    "ollama>=0.6.0",
    "psycopg[binary,pool]>=3.2.12",
    "pycryptodome>=3.23.0",
]
